### PR TITLE
New ping API

### PR DESCRIPTION
**Pull request by owlishDeveloper**
@imbstack @djmitche  r?

### CODE REVIEW

**Comment by jonasfj** [comment]
Same issue as others... I'm going to close this... scheduler is deprecated... So let's just not touch it unless we have some critical reason to.

**Comment by djmitche** [comment]
It's worth noting, that the scheduler is still running, just its *use* is deprecated.  When we turn it off, we have a process for marking the corresponding github repo as deprecated.

**Comment by owlishDeveloper** [comment]
@djmitche @jonasfj  So, do I re-open this or not?

**Comment by jonasfj** [comment]
I suggest we don't change anything unless there is a bug.

**Pull request closed without merging**
